### ISSUE TITLE
Subtasks lose their indent when switching columns

### ISSUE THREAD

**Issue by FearTheBadger** [ErikaRS/task-list-kanban#17]
Moving items to any new column, messes with the hierarchy of the task.

if I have:
- [ ] This is a parent task #Later
     - [ ] This is a sub #Later

and I move `This is a sub` to #Soonish, I get the following

- [ ] This is a parent task #Later
- [ ] This is a sub #Soonish
